# Generated by Django 5.0.3 on 2024-03-27 13:09

import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=ulid.ULID, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('file_url', models.URLField(unique=True)),
                ('file_hash', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
