# Generated by Django 5.0.3 on 2024-03-27 13:09

import django.db.models.deletion
import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='elo', serialize=False, to='image.image')),
                ('score', models.FloatField(default=1500)),
                ('n_games', models.PositiveIntegerField(default=0)),
                ('n_wins', models.PositiveIntegerField(default=0)),
                ('n_losses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.CharField(default=ulid.ULID, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('previous_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='elo.elo')),
            ],
        ),
    ]
