# Generated by Django 5.0.3 on 2024-03-27 22:34

import django.db.models.deletion
import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(default=ulid.ULID, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('k', models.FloatField(blank=True, editable=False, null=True)),
                ('winner_score_old', models.FloatField(blank=True, editable=False, null=True)),
                ('winner_score_new', models.FloatField(blank=True, editable=False, null=True)),
                ('winner_diff', models.FloatField(blank=True, editable=False, null=True)),
                ('loser_score_old', models.FloatField(blank=True, editable=False, null=True)),
                ('loser_score_new', models.FloatField(blank=True, editable=False, null=True)),
                ('loser_diff', models.FloatField(blank=True, editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='elo.elo')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='elo.elo')),
            ],
        ),
    ]
