# Generated by Django 5.0.3 on 2024-03-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_alter_match_loser_alter_match_winner'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elo',
            name='image',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='elo', serialize=False, to='image.image'),
        ),
        migrations.AlterField(
            model_name='elo',
            name='n_games',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='elo',
            name='n_losses',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='elo',
            name='n_wins',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='elo',
            name='score',
            field=models.FloatField(default=1500, editable=False),
        ),
        migrations.AlterField(
            model_name='elohistory',
            name='elo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='elo.elo'),
        ),
        migrations.AlterField(
            model_name='elohistory',
            name='new_score',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='elohistory',
            name='previous_score',
            field=models.FloatField(editable=False),
        ),
    ]
